config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about' => 'static_pages#about'
  get '/help' => 'static_pages#help'
  get '/contact' => 'static_pages#contact'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  delete '/signout' => 'sessions#destroy'

  get '/dashboard' => 'dashboard#show'

  resources :tweets

  resources :users, only: [:show]
  

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base

	belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	def show
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by_email(params[:email])

		if user
			if user.authenticate(params[:password])
				session[:user_id] = user.id
				flash[:notice] = "You are signed in."
				redirect_to user_path(user)
			else
				flash[:notice] = "Wrong password."
				redirect_to signin_path
			end
			
		else
			flash[:notice] = "Wrong email."
			redirect_to signin_path
		end
		
	end

	def destroy
		session[:user_id] = nil

		flash[:notice] = "You are signed out."
		redirect_to root_path
	end

end
 

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end

	def about
	end

	def help
	end

	def contact
	end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
	def new
	end

	def create
		Tweet.create(content: params[:tweet],
					user_id: session[:user_id])
	end

	def index
		user = User.find_by_id(session[:user_id])
		@tweets = user.tweets
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
	end
	
	def create
		user = User.create(name: params[:name], 
					email: params[:email],
					password: params[:password],
					password_confirmation: params[:password_confirmation])
		flash[:notice] = "Your account has been created."

		session[:user_id] = user.id
		redirect_to user_path(user.id)
	end

	def show
		@user = User.find_by_id(params[:id])
		@tweets = @user.tweets


	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_footer.html.erb
<footer class="footer">
	<small>
		<a href="http://railstutorial.org/">Rails Tutorial</a> by Michael Hartl
	</small>
	<nav> 
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact",contact_path %></li>
			<li><a href="<%= about_path %>"> News</a> </li>
		</ul>
	</nav>
</footer>

app/views/application/_header.html.erb
<header class= "navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "sample app", '#', id: "logo" %>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "Help", help_path %></li>
					
					<% if session[:user_id].blank? %>
						<li><%= link_to "Sign in", signin_path %></li>
					<% else %>
						<li><%= link_to "Tweet", new_tweet_path %></li>
						<li><%= link_to "Sign Out", signout_path, method: :delete %></li>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/dashboard/show.html.erb
<% if session[:user_id] %>
	<% user = User.find(session[:user_id]) %>
	<h2>Welcome, <%= user.name %>!</h2>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nguyen - <%= yield :title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render "header" %>

	<div class="container">
		<%= flash[:notice] %>
		<%= yield %>
		
		<%= render "footer" %>

	</div>

</body>
</html>

app/views/static_pages/about.html.erb
<% content_for :title do %>
About
<% end %>

<h1>
About
</h1>
<h2>
	"All About Cats"
</h2>
<h3>Did you know?
</h3>

<nav>
	<ul>
		<li>On average, cats spend 2/3 of every day sleeping. That means a nine-year-old cat has been awake for only three years of its life</li>
		<li>Cats are cute. No arguments there</li>
		<li>The technical term for a cat’s hairball is a “bezoar.”</li>
		<li>Cats are still cute.</li>
		<li>Cats make about 100 different sounds. Dogs make only about 10.</li>
	</ul>
</nav>

app/views/static_pages/contact.html.erb
<%= content_for :title do %>
Contact
<% end %>

<h1>Contact
</h1>

<p>For further information about one of the cutest animals in the world (other than pandas and puppies),
</p>
<p>do not hesitate to send me a postcard and I will get back to you as soon as I can.
</p>
<p>POSTCARDS <strong><u>ONLY</u>!</strong>
</p>
<p>Thank you very much! :D
</p>

app/views/static_pages/help.html.erb
<% content_for :title do %>
Help
<% end %>

<h1>Help</h1>

<p>If you need any help, please call <strong>911</strong>.</p>

app/views/static_pages/home.html.erb
<% content_for :title do %> 
Home
<% end %>

<div class="center hero-unit">
	<h1>Welcome to the Sample App</h1>

	<h2>
		This is the home page for the <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a> sample application
	</h2>

	<%= link_to "Sign up now!", signup_path , class: "btn btn-large btn-primary" %>

</div>

<%= link_to image_tag("cat.jpeg", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/tweets/index.html.erb
<h3>Tweets</h3>
<ul>
<% @tweets.each do |tweet| %>
<li>
	<%= tweet.user.name %>
	<%= tweet.content %> - <%= tweet.created_at %>
</li>
<% end %>
</ul>

app/views/tweets/new.html.erb
<h3>Tweet</h3>

<%= form_tag tweets_path do %>
	<%= label_tag "Tweet" %>
	<%= text_area_tag :tweet %>

	<br/>
	<%= submit_tag "Tweet" %>

<% end %>

app/views/users/new.html.erb
<h3>Signup</h3>

<%= form_tag signup_path do %>
	<%= label_tag "Name" %>
	<%= text_field_tag :name %>

	<%= label_tag "Email" %>
	<%= text_field_tag :email %>

	<%= label_tag "Password" %>
	<%= password_field_tag :password %>

	<%= label_tag "Password Confirmation" %>
	<%= password_field_tag :password_confirmation %>
	
	<br/>
	<%= submit_tag "Create my account" %>
<% end %>

app/views/users/show.html.erb
<div class="row">
	<aside class="span4">
		<section>
			<img src="<%= "http://www.gravatar.com/avatar/" + Digest::MD5::hexdigest(@user.email) + ".png"%>">
			<h1>
				<%= @user.name %>
			</h1>
		</section>
	</aside>

	<div class="span8">
		<ul class="tweets"> 
			<% @tweets.each do |tweet| %>
			<li>
			<span class="content"><%= tweet.content %></span>
			<span class="timestamp"> 
			Posted <%= time_ago_in_words(tweet.created_at) %> ago. 
			</span>
			</li>
			<% end %>
		</ul>
	</div>
</div>